### ISSUE TITLE
Providing a relative path to base_path flag doesn't work

### ISSUE THREAD

**Issue by LiadAzulay** [hasadna/hasadna#54]
When trying to provide a relative path of base_path flag, it's doesn't work with:
`bazel run //tools/reviewer/aa:aa_tool -- init --base_path </path/to/base/folder>`
It only works when providing an absolute path.

**Comment by LiadAzulay** [comment]
when trying to provide relative path of base_path flag it's doesn't working in the command "bazel run //tools/reviewer/aa:aa_tool -- init --base_path </path/to/base/folder>".
only working when providing absolute path.

**Comment by oferb** [comment]
Actually, that's working as intended. Absolute paths are fine.
